### ISSUE TITLE
Make the lib compliant with compilation server

### ISSUE THREAD

**Issue by kiroukou** [kevinresol/quick-enums#1]
I just encountered an issue today with the lib.

/src/react/native/component/props/TextProps.hx:22: characters 20-62 : Type not found : enums.Enum_10

Seems that the lib doesn't handle very well with the cache system behind the compilation server.

I don't have a solution right now, but I may investigate further later if you confirm the problem on your side.

Thanks!

**Comment by kevinresol** [comment]
Sorry but I don't use compilation server. If you find a fix, feel free to PR.

**Comment by kiroukou** [comment]
FYI, I'll make a PR someday with a version of react-native externs without quick-enums use.

I'll make sure it is as complete as possible.

I wasn't able to make le compiler happy with quick-enums on vscode.
(I'm not sure how to resolve the issue, and IMHO it is far better to create real enums ;) )
